### ISSUE TITLE
dataset release

### ISSUE THREAD

**Issue by YaoShunyu19** [chencn2020/Seagull#1]
Thanks for your interesting and meaningful work. When will you share SEAGULL-100w and SEAGULL-3k? Thanks again.

**Comment by chencn2020** [comment]
Thank you for your attention to our work : )  
We are currently working hard to organize the code and dataset, and will release them soon.

**Comment by YaoShunyu19** [comment]
Thank you so much for your quick reply to my question, I'm looking forward to the dataset announcement!
