### ISSUE TITLE
Questions about gradio demo and inference on custom dataset

### ISSUE THREAD

**Issue by whycantfindaname** [chencn2020/SEAGULL#5]
Thanks for your wonderful work! 
However, I’ve noticed a minor issue in the offline demo. When switching to mask-based ROIs (bounding boxes), the input image seems to be cropped from the original, as can be seen in the following two images. This issue doesn't occur with point-based ROIs.
Input image:
![image](https://github.com/user-attachments/assets/45286a6d-3534-49b8-97b5-80c15072c10b)
Mask on Image:
![image](https://github.com/user-attachments/assets/b0eee16c-7752-4696-905d-f50028b95256)
Additionally, I have a question about inference on my custom dataset, which includes both images and bounding box coordinates. If I choose not to use SAM  and instead directly provide the rectangular box mask to the model, how should I go about this? Will the absence of SAM impact the model's performance?
Thanks for your time.

**Comment by chencn2020** [comment]
Thank you for your attention to our work! 

For the first issue, we will try to reproduce the problem on our own device and get back to you as soon as possible with more information.

The absence of SAM will not affect the model’s performance. If you choose to use bounding box coordinates directly, you can first generate the corresponding mask based on these coordinates and provide it as input to SEAGULL. 
We will add a module that uses rectangular box to indicate ROIs in the demo. 

If you need to test a large amount of data, we will also release the testing scripts as soon as possible.

**Comment by whycantfindaname** [comment]
> Thank you for your attention to our work!
> 
> For the first issue, we will try to reproduce the problem on our own device and get back to you as soon as possible with more information.
> 
> The absence of SAM will not affect the model’s performance. If you choose to use bounding box coordinates directly, you can first generate the corresponding mask based on these coordinates and provide it as input to SEAGULL. We will add a module that uses rectangular box to indicate ROIs in the demo.
> 
> If you need to test a large amount of data, we will also release the testing scripts as soon as possible.

Thanks! Looking forward to it!

**Comment by chencn2020** [comment]
Hi!

For the first issue, it appears to be a recurring bug with Gradio.  If you know how to fix it, please submit a Pull Request, which would be greatly beneficial to the community.

And the module that uses boxes points to indicate ROIs is added in the demo. We've also released a testing script. All details are available in the README.

Feel free to let me know if you need further assistance!

**Comment by whycantfindaname** [comment]
> Hi!
> 
> For the first issue, it appears to be a recurring bug with Gradio. If you know how to fix it, please submit a Pull Request, which would be greatly beneficial to the community.
> 
> And the module that uses boxes points to indicate ROIs is added in the demo. We've also released a testing script. All details are available in the README.
> 
> Feel free to let me know if you need further assistance!

Thanks! I will test it lately.
